const env = process.env.NODE_ENV || 'development'
const credentials = require(`./.credentials.${env}`)
const sberUserName = 'sberUserName'
const port = 3000
const domen = 'simple.loc'
const protocol = 'http'
const host = 'localhost'
const user = 'admin_chiptuning'
const password = 'Vagon_3611'
const database = 'chiptuning'
const fileMaxSize = 1024*1024
module.exports = { credentials , domen, protocol, host, user, password, database, port, sberUserName, fileMaxSize }
